### ISSUE TITLE
Tagging strategy for automated releases

### ISSUE THREAD

**Issue by llarsson** [elastisys/ck8s-starter-nodejs#2]
This is entering almost the philosophical realm now: if I don't change anything about my application (it's still `v1.11.3` as far as my features are concerned), but I *do* rebuild the image to pull in new dependencies and avoid vulnerabilities in the base image, something needs to still trigger a redeployment.

If we would always have `${GITHUB_REF}-${GITHUB_SHA}`, simply restarting the workflow will do what I want in that case.

That's how I've kept it in the first pull request for this repo, which I am about to make.

_Originally posted by @llarsson in https://github.com/elastisys/ck8s-starter-nodejs/issues/1#issuecomment-1080436251_

**Comment by cristiklein** [comment]
Let's get really philosophical. :smile: 

My understanding of [SemVer 2.0.0](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) is that changing dependencies, whether via `packages.json` or via a new base image should bump the patch or minor version of your application:

> What should I do if I update my own dependencies without changing the public API?
>
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. We would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

An alternative practice that I noticed to distinguish between "application dependency changes" and "base image changes" is to use a TAG like `myapp:1.1.1-nodejs16.1.1`.

I do understand that many app developers are happy with `FROM node:16` and that is a legitimate change management decision. But I'd argue that re-using major-minor-patch container image tags just because "my application didn't really change" is not proper change management.

**Comment by llarsson** [comment]
Philosophy again!

OK, makes perfect sense w.r.t. direct dependencies, such as ones listed in your `package.json` file, for instance. But that means I've fundamentally changed something in my code repo, and therefore, I have a new commit as well. The "thing that is built" is different.

But what about stuff in the underlying image? Either because a new `node:16` has been released, or because you have `RUN apt update && apt install some-native-library` as part of your `Dockerfile`? Nothing in the code repo has changed then -- so the "thing that is built" is the same... right?

Many **will** just have `FROM node:16` as their base image, so there **will** for sure be a different container popping out if I build today and if I build one month from now.

I've had this discussion with many people over the years and it's never been clear cut.
